version: '3'

services:
  game:
    build: .
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XDG_RUNTIME_DIR}/pulse:/run/user/1000/pulse:ro
      - .:/app
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    devices:
      - /dev/video0:/dev/video0
      - /dev/snd:/dev/snd
    network_mode: host
    # For Mac users, you'll need to run XQuartz and allow connections from network clients
    # For Windows users, you'll need to use an X server like VcXsrv or Xming
